# -*- coding: utf-8 -*-
"""Indian Railway Station.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5A9JV7v2RLh6xCiUQoyiokhtVO9fnRC
"""

import pandas as pd
import numpy as np

dataset = pd.read_csv('/content/INDIAN RAILWAY STATION.csv')

pd.set_option('display.max_rows', None)
dataset

dataset.dropna(thresh=len(dataset.columns)-1, inplace=True)

dataset.shape #8938 total station should be

dataset.head(6)

dataset = dataset[dataset['0'] != 'Code']

dataset.shape

dataset.head(6)

dataset.rename(columns={'0': 'CODE', '1': 'STATION NAME', '2': 'RAILWAY ZONE', '3': 'STATION ADDRESS'}, inplace=True)

dataset.head(6)

dataset = dataset.drop('Unnamed: 0', axis=1)

dataset = dataset.reset_index(drop=True)

dataset.head(5 )

dataset.to_csv("INDIAN RAILWAY STATION LIST.csv")



